AWSTemplateFormatVersion: '2010-09-09'
Description: Create EC2 with Security Group for SSH using existing KeyPair and VPC

Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to SSH into instance
    Type: AWS::EC2::KeyPair::devops-key

  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t3.micro
      - t3.small
      - t3.medium

  VpcId:
    Description: The ID of an existing VPC (e.g., vpc-abc123)
    Type: AWS::EC2::VPC::Id

Resources:
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH access
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: ami-0c02fb55956c7d316  # Update to correct AMI ID for your region
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
      Tags:
        - Key: Name
          Value: MyCloudFormationInstance

Outputs:
  PublicIP:
    Description: Public IP of the instance
    Value: !GetAtt EC2Instance.PublicIp

  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref EC2Instance
